package model;

public class CustomerModel {

    /*
        --> This model mainly for saving and getting customer full details.
     */


    private String accountNumber; // * Account number is automatically generated.
    private String name;  // * Customer's full name
    private int age; // * Customer age is generated by the system at 'OpenNewAccountController'
    private String sex; // * "Male" or "Female"
    private String accountType; // * Currently system has only one account type 'savings account'
    private String customerAddress; // * Customer's address
    private String telephoneNumber; // * Customer's telephone number
    private String customerBirthday; // * Customer's birthday
    private String joinedDate; // * This is date of account created. This saved by the system.
    private String customerNIC; // * Customer's NIC
    private String customerEmail; // * Customer's E-mail
    private String rationLoan; // * if there is a ration loan, It's ID
    private String loanByDeposit; // * if there is a loan by deposit, It's ID
    private String instantLoan; // * if there is a instant loan, It's ID

    public CustomerModel(String accountNumber, String name, int age, String sex,
                         String accountType, String customerAddress, String telephoneNumber,
                         String customerBirthday, String joinedDate, String customerNIC,
                         String customerEmail, String rationLoan, String instantLoan,
                         String loanByDeposit) {
        this.accountNumber = accountNumber;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.accountType = accountType;
        this.customerAddress = customerAddress;
        this.telephoneNumber = telephoneNumber;
        this.customerBirthday = customerBirthday;
        this.joinedDate = joinedDate;
        this.customerNIC = customerNIC;
        this.customerEmail = customerEmail;
        this.rationLoan = rationLoan;
        this.instantLoan = instantLoan;
        this.loanByDeposit = loanByDeposit;
    }

    public CustomerModel(){}


    @Override
    public String toString() {
        return "CustomerModel{" +
                "accountNumber='" + accountNumber + '\'' +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", sex='" + sex + '\'' +
                ", accountType='" + accountType + '\'' +
                ", customerAddress='" + customerAddress + '\'' +
                ", telephoneNumber='" + telephoneNumber + '\'' +
                ", customerBirthday='" + customerBirthday + '\'' +
                ", joinedDate='" + joinedDate + '\'' +
                ", customerNIC='" + customerNIC + '\'' +
                ", customerEmail='" + customerEmail + '\'' +
                ", rationLoan='" + rationLoan + '\'' +
                ", instantLoan='" + instantLoan + '\'' +
                ", loanByDeposit='" + loanByDeposit + '\'' +
                '}';
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public String getCustomerAddress() {
        return customerAddress;
    }

    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    public String getCustomerBirthday() {
        return customerBirthday;
    }

    public void setCustomerBirthday(String customerBirthday) {
        this.customerBirthday = customerBirthday;
    }

    public String getJoinedDate() {
        return joinedDate;
    }

    public void setJoinedDate(String joinedDate) {
        this.joinedDate = joinedDate;
    }

    public String getCustomerNIC() {
        return customerNIC;
    }

    public void setCustomerNIC(String customerNIC) {
        this.customerNIC = customerNIC;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public String getRationLoan() {
        return rationLoan;
    }

    public void setRationLoan(String rationLoan) {
        this.rationLoan = rationLoan;
    }

    public String getInstantLoan() {
        return instantLoan;
    }

    public void setInstantLoan(String instantLoan) {
        this.instantLoan = instantLoan;
    }

    public String getLoanByDeposit() {
        return loanByDeposit;
    }

    public void setLoanByDeposit(String loanByDeposit) {
        this.loanByDeposit = loanByDeposit;
    }
}
